### ISSUE TITLE
[YBUG.IO] Hello to you, when I get to the...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#701]
Hello to you, when I get to the soveryn application, after about 30 seconds the screen disappears and I can't see anything. I can't do anything. I'm using Chrome browser and tried with Edge. Thanks for help!

*Source url:* https://live.sovryn.app/stats
*Reported by:* patrick.jacquesig@gmail.com
*Reported at:* 14 Apr at 12:50 UTC

*Location:* CA, Quebec, Trois-Rivières
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1366x768
*Viewport:* 1366x625

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/0dabbk0mmw57n1ttw54g/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg0MDQ2MzksImRhdGEiOnsicmVwb3J0IjoiMGRhYmJrMG1tdzU3bjF0dHc1NGciLCJ1c2VyIjoiR2l0SHViIn19.6PW1C4W8_CKCbiGWuX6pwyDfgGjk__yMC1LUrz2lNvc)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/0dabbk0mmw57n1ttw54g](https://ybug.io/dashboard/reports/detail/0dabbk0mmw57n1ttw54g)

**Comment by creed-victor** [comment]
Error log:
```
 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.3.63e22893.chunk.js:2:4698251
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ls (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4698251)
    at fc (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4711442)
    at e.unstable_runWithPriority (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4732184)
    at ji (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4656397)
    at dc (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4709300)
    at $s (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4705482)
    at https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4656688
    at e.unstable_runWithPriority (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4732184)
    at ji (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4656397)
    at Gi (https://live.sovryn.app/static/js/3.63e22893.chunk.js:2:4656633)
```

**Comment by soulBit** [comment]
Issue should be resolved now
